image: registry.github.com/MASS4ORG/fanstatic:alpine

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_SUBMODULE_UPDATE_FLAGS: --remote

stages:
  - test
  - pages

test:
  stage: test
  script:
    - fanstatic --version
    - fanstatic

pages:
  stage: pages
  script:
    - fanstatic
  artifacts:
    paths:
      - public
  # rules:
  # - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
